# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiFare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.IntegerField()),
                ('lpepPickupDatetime', models.DateTimeField()),
                ('lpepDropoffDatetime', models.DateTimeField()),
                ('storeAndFwdFlag', models.CharField(max_length=1)),
                ('rateCodeId', models.IntegerField()),
                ('pickupLongitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickupLatitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoffLongitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoffLatitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('passengerCount', models.IntegerField()),
                ('tripDistance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fareAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mtaTax', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tollsAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ehailFee', models.CharField(max_length=10)),
                ('improvementSurcharge', models.DecimalField(decimal_places=2, max_digits=9)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paymentType', models.IntegerField()),
                ('tripType', models.IntegerField()),
            ],
        ),
    ]
