# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fareAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mtaTax', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tollsAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ehailFee', models.CharField(max_length=10)),
                ('improvementSurcharge', models.DecimalField(decimal_places=2, max_digits=9)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paymentType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxiDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxiDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxiLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.IntegerField()),
                ('storeAndFwdFlag', models.CharField(max_length=1)),
                ('rateCodeId', models.IntegerField()),
                ('passengerCount', models.IntegerField()),
                ('tripDistance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tripType', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='dropoffLatitude',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='dropoffLongitude',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='ehailFee',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='fareAmount',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='improvementSurcharge',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='lpepDropoffDatetime',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='lpepPickupDatetime',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='mtaTax',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='passengerCount',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='paymentType',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='pickupLatitude',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='pickupLongitude',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='rateCodeId',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='storeAndFwdFlag',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='tipAmount',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='tollsAmount',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='totalAmount',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='tripDistance',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='tripType',
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='vendorId',
        ),
    ]
