# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0002_auto_20161129_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxifare',
            name='additionalFareInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataload.FareInfo'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='fareDropoffLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoffLocation', to='dataload.TaxiLocation'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='fareDropoffTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoffTime', to='dataload.TaxiDateTime'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='farePickupLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupLocation', to='dataload.TaxiLocation'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='farePickupTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupTime', to='dataload.TaxiDateTime'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='fareTripInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataload.TripInfo'),
        ),
    ]
