# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0003_auto_20161129_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateCodeId', models.IntegerField()),
                ('rateType', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAndForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeAndFwdFlag', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='taxifare',
            name='fareTripInfo',
        ),
        migrations.AddField(
            model_name='fareinfo',
            name='passengerCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fareinfo',
            name='tripDistance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='fareinfo',
            name='tripType',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taxilocation',
            name='borough',
            field=models.CharField(default='unknown', max_length=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='fareAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='improvementSurcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='mtaTax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='paymentType',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='tipAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='tollsAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fareinfo',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='TripInfo',
        ),
        migrations.AddField(
            model_name='taxifare',
            name='rateCodeInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataload.RateCode'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='storeAndForwardInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataload.StoreAndForward'),
        ),
        migrations.AddField(
            model_name='taxifare',
            name='vendorInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataload.VendorInfo'),
        ),
    ]
