# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0004_auto_20161130_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxidatetime',
            name='day',
            field=models.CharField(default='Friday', max_length=15),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='dayOfMonth',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='dayOfWeek',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='dayOfYear',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='hour',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='minute',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='month',
            field=models.CharField(default='January', max_length=15),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='monthOfYear',
            field=models.IntegerField(default=2016, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='second',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='weekOfYear',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='taxidatetime',
            name='year',
            field=models.IntegerField(default=2016, max_length=2),
        ),
        migrations.AlterField(
            model_name='taxifare',
            name='fareDropoffTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoffTime', to='dataload.TaxiDatetime'),
        ),
        migrations.AlterField(
            model_name='taxifare',
            name='farePickupTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupTime', to='dataload.TaxiDatetime'),
        ),
    ]
