# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0012_auto_20161205_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeandforward',
            old_name='store_and_fwd_flaga',
            new_name='store_and_fwd_flag',
        ),
        migrations.AlterField(
            model_name='taxifare',
            name='fare_dropoff_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoffTime', to='dataload.TaxiDatetime'),
        ),
        migrations.AlterField(
            model_name='taxifare',
            name='fare_pickup_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupTime', to='dataload.TaxiDatetime'),
        ),
    ]
